Repository cloudquery/cq-provider-azure, pull requests merged in 2022-03, with the labels that each got.

#164 fix: Typo in resource name (container.registRies)
  resources/provider/provider.go
Labels: fix

#174 chore: Update SDK
  client/errors.go
  go.mod
  go.sum
Labels: ignore-for-release

#172 feat: Add network_rule_set field to eventhub
  client/services/eventhub.go
  client/services/mocks/eventhub.go
  docs/tables/azure_eventhub_namespaces.md
  resources/provider/migrations/postgres/8_v0.8.0.down.sql
  resources/provider/migrations/postgres/8_v0.8.0.up.sql
  resources/provider/migrations/timescale/8_v0.8.0.down.sql
  resources/provider/migrations/timescale/8_v0.8.0.up.sql
  resources/services/eventhub/namespaces.go
  resources/services/eventhub/namespaces_mock_test.go
Labels: feat

#173 feat: Add backup long term retention to sql db
  client/services/mocks/sql_database.go
  client/services/sql.go
  docs/tables/azure_sql_databases.md
  resources/provider/migrations/postgres/10_v0.8.0.down.sql
  resources/provider/migrations/postgres/10_v0.8.0.up.sql
  resources/provider/migrations/timescale/10_v0.8.0.down.sql
  resources/provider/migrations/timescale/10_v0.8.0.up.sql
  resources/services/sql/databases.go
  resources/services/sql/servers_mock_test.go
Labels: feat

#168 chore: Synced file(s) with cloudquery/.github
  .github/workflows/lint_doc.yml
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
Labels: ignore-for-release

#158 feat: Account locations
  client/services/mocks/subscriptions.go
  client/services/services.go
  client/services/subscriptions.go
  docs/tables/azure_account_locations.md
  resources/provider/migrations/postgres/10_v0.8.0.down.sql
  resources/provider/migrations/postgres/10_v0.8.0.up.sql
  resources/provider/migrations/timescale/10_v0.8.0.down.sql
  resources/provider/migrations/timescale/10_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/account/account_locations.go
  resources/services/account/account_locations_mock_test.go
  resources/services/subscription/subscriptions_mock_test.go
Labels: feat

#157 feat: Add Security Assessments resource
  client/services/mocks/network.go
  client/services/mocks/security.go
  client/services/security.go
  client/services/services.go
  docs/tables/azure_security_assessments.md
  resources/provider/migrations/postgres/9_v0.8.0.down.sql
  resources/provider/migrations/postgres/9_v0.8.0.up.sql
  resources/provider/migrations/timescale/9_v0.8.0.down.sql
  resources/provider/migrations/timescale/9_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/security/assessments.go
  resources/services/security/assessments_mock_test.go
Labels: feat

#159 feat: Implement StreamAnalytics Jobs
  client/services/mocks/streamanalytics.go
  client/services/services.go
  client/services/streamanalytics.go
  docs/tables/azure_streamanalytics_jobs.md
  resources/provider/migrations/postgres/11_v0.8.0.down.sql
  resources/provider/migrations/postgres/11_v0.8.0.up.sql
  resources/provider/migrations/timescale/11_v0.8.0.down.sql
  resources/provider/migrations/timescale/11_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/streamanalytics/jobs.go
  resources/services/streamanalytics/jobs_mock_test.go
Labels: feat

#165 feat: Add Logic App Workflow resource
  client/services/logic.go
  client/services/mocks/logic.go
  client/services/services.go
  docs/tables/azure_logic_app_workflows.md
  resources/provider/migrations/postgres/12_v0.8.0.down.sql
  resources/provider/migrations/postgres/12_v0.8.0.up.sql
  resources/provider/migrations/timescale/12_v0.8.0.down.sql
  resources/provider/migrations/timescale/12_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/logic/app_workflows.go
  resources/services/logic/app_workflows_test.go
Labels: feat

#170 feat: Add vnet connection to web app
  docs/tables/azure_web_apps.md
  resources/provider/migrations/postgres/13_v0.8.0.down.sql
  resources/provider/migrations/postgres/13_v0.8.0.up.sql
  resources/provider/migrations/timescale/13_v0.8.0.down.sql
  resources/provider/migrations/timescale/13_v0.8.0.up.sql
  resources/services/web/apps.go
  resources/services/web/apps_mock_test.go
Labels: feat

#149 feat: Added search services
  client/client.go
  client/services/mocks/search.go
  client/services/search.go
  client/services/services.go
  docs/tables/azure_search_service_private_endpoint_connections.md
  docs/tables/azure_search_service_shared_private_link_resources.md
  docs/tables/azure_search_services.md
  go.mod
  resources/provider/migrations/postgres/14_v0.8.0.down.sql
  resources/provider/migrations/postgres/14_v0.8.0.up.sql
  resources/provider/migrations/timescale/14_v0.8.0.down.sql
  resources/provider/migrations/timescale/14_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/search/services.go
  resources/services/search/services_mock_test.go
Labels: feat

#156 feat: Added batch accounts
  client/services/batch.go
  client/services/mocks/batch.go
  client/services/services.go
  docs/tables/azure_batch_account_private_endpoint_connections.md
  docs/tables/azure_batch_accounts.md
  resources/provider/migrations/postgres/15_v0.8.0.down.sql
  resources/provider/migrations/postgres/15_v0.8.0.up.sql
  resources/provider/migrations/timescale/15_v0.8.0.down.sql
  resources/provider/migrations/timescale/15_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/batch/accounts.go
  resources/services/batch/accounts_mock_test.go
Labels: feat

#179 chore: Merge migration files
  resources/provider/migrations/postgres/10_v0.8.0.down.sql
  resources/provider/migrations/postgres/10_v0.8.0.up.sql
  resources/provider/migrations/postgres/11_v0.8.0.down.sql
  resources/provider/migrations/postgres/11_v0.8.0.up.sql
  resources/provider/migrations/postgres/12_v0.8.0.down.sql
  resources/provider/migrations/postgres/12_v0.8.0.up.sql
  resources/provider/migrations/postgres/13_v0.8.0.down.sql
  resources/provider/migrations/postgres/13_v0.8.0.up.sql
  resources/provider/migrations/postgres/14_v0.8.0.down.sql
  resources/provider/migrations/postgres/14_v0.8.0.up.sql
  resources/provider/migrations/postgres/15_v0.8.0.down.sql
  resources/provider/migrations/postgres/15_v0.8.0.up.sql
  resources/provider/migrations/postgres/8_v0.8.0.down.sql
  resources/provider/migrations/postgres/8_v0.8.0.up.sql
  resources/provider/migrations/postgres/9_v0.8.0.down.sql
  resources/provider/migrations/postgres/9_v0.8.0.up.sql
  resources/provider/migrations/timescale/10_v0.8.0.down.sql
  resources/provider/migrations/timescale/10_v0.8.0.up.sql
  resources/provider/migrations/timescale/11_v0.8.0.down.sql
  resources/provider/migrations/timescale/11_v0.8.0.up.sql
  resources/provider/migrations/timescale/12_v0.8.0.down.sql
  resources/provider/migrations/timescale/12_v0.8.0.up.sql
  resources/provider/migrations/timescale/13_v0.8.0.down.sql
  resources/provider/migrations/timescale/13_v0.8.0.up.sql
  resources/provider/migrations/timescale/14_v0.8.0.down.sql
  resources/provider/migrations/timescale/14_v0.8.0.up.sql
  resources/provider/migrations/timescale/15_v0.8.0.down.sql
  resources/provider/migrations/timescale/15_v0.8.0.up.sql
  resources/provider/migrations/timescale/8_v0.8.0.down.sql
  resources/provider/migrations/timescale/8_v0.8.0.up.sql
  resources/provider/migrations/timescale/9_v0.8.0.down.sql
  resources/provider/migrations/timescale/9_v0.8.0.up.sql
Labels: ignore-for-release

#181 chore: Fix terraform workflows
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#183 chore: Move terraform workflows to work without OIDC
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#184 test: Add search service terraform
  terraform/search/local/main.tf
  terraform/search/modules/test/providers.tf
  terraform/search/modules/test/services.tf
  terraform/search/modules/test/terraform.tf
  terraform/search/modules/test/variables.tf
  terraform/search/prod/.terraform.lock.hcl
  terraform/search/prod/main.tf
  terraform/search/prod/terraform.tf
Labels: test

#186 chore: Move terraform workflows to env variables
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  scripts/terraform-apply-all.sh
  scripts/terraform-fmt-change-only.sh
  scripts/terraform-plan-change-only.sh
  scripts/terraform-validate-all.sh
  scripts/terraform-validate-change-only.sh
Labels: ignore-for-release

#187 test: Add logic_app_workflow terraform
  scripts/terraform-apply-all.sh
  scripts/terraform-fmt-change-only.sh
  scripts/terraform-plan-change-only.sh
  scripts/terraform-validate-all.sh
  scripts/terraform-validate-change-only.sh
  terraform/logic/local/main.tf
  terraform/logic/modules/test/app_workflows.tf
  terraform/logic/modules/test/providers.tf
  terraform/logic/modules/test/terraform.tf
  terraform/logic/modules/test/variables.tf
  terraform/logic/prod/.terraform.lock.hcl
  terraform/logic/prod/main.tf
  terraform/logic/prod/terraform.tf
Labels: test

#189 chore: Add -auto-approve to terraform apply
  scripts/terraform-apply-changes-only.sh
  scripts/terraform-plan-change-only.sh
  terraform/search/modules/test/services.tf
Labels: ignore-for-release

#190 test: Add terraforms for streamanalytics and security services
  resources/services/batch/accounts.go
  resources/services/compute/virtual_machines.go
  resources/services/logic/app_workflows.go
  resources/services/logic/app_workflows_test.go
  resources/services/search/services.go
  resources/services/security/assessments.go
  resources/services/streamanalytics/jobs.go
  terraform/batch/modules/test/accounts.tf
  terraform/search/modules/test/services.tf
  terraform/security/local/main.tf
  terraform/security/modules/test/assessments.tf
  terraform/security/modules/test/providers.tf
  terraform/security/modules/test/terraform.tf
  terraform/security/modules/test/variables.tf
  terraform/security/prod/.terraform.lock.hcl
  terraform/security/prod/main.tf
  terraform/security/prod/terraform.tf
  terraform/sql/modules/test/managed_instances.tf
  terraform/sql/modules/test/servers.tf
  terraform/streamanalytics/local/main.tf
  terraform/streamanalytics/modules/test/jobs.tf
  terraform/streamanalytics/modules/test/providers.tf
  terraform/streamanalytics/modules/test/terraform.tf
  terraform/streamanalytics/modules/test/variables.tf
  terraform/streamanalytics/prod/.terraform.lock.hcl
  terraform/streamanalytics/prod/main.tf
  terraform/streamanalytics/prod/terraform.tf
Labels: test

#191 chore: Comment in PR on terraform plan
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
Labels: ignore-for-release

#193 chore: Add infracost
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
  scripts/terraform-plan-change-only.sh
  terraform/batch/modules/test/accounts.tf
Labels: ignore-for-release

#199 chore: Sync form .github
  .github/workflows/README
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  CODEOWNERS
  CODE_OF_CONDUCT.md
Labels: ignore-for-release

#200 chore: Sync form .github
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#201 chore: Sync form .github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#204 chore: Sync form .github
  CONTRIBUTING.md
Labels: ignore-for-release

#203 feat: Update cq-provider-sdk to v0.8.12
  go.mod
  go.sum
Labels: feat

#205 chore: Sync form .github
  Makefile
Labels: ignore-for-release

#206 docs: Add 'resources' to config, comment-out optional field
  docs/index.md
Labels: docs

#208 chore: Sync form .github
  docs/contributing/issue_reporting.md
Labels: ignore-for-release

#209 feat: Update SDK version v0.8.13
  go.mod
  go.sum
Labels: feat

#211 chore: Sync form .github
  .github/workflows/issue_to_project.yml
  Makefile
Labels: ignore-for-release

#214 chore: Update SDK
  go.mod
  go.sum
Labels: ignore-for-release

#216 fix: Migrations for v0.6.0
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
Labels: fix
