Repository cloudquery/cq-provider-azure, pull requests merged in 2022-01, with the labels that each got.

#117 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/doc_validation.yml
  .github/workflows/golang_lint.yml
  .github/workflows/mock_test.yml
  .github/workflows/pr_title.yml
  .github/workflows/release.yml
  .golangci.yml
Labels: chore

#91 fix: Table `azure_network_virtual_networks` column types changed
  CHANGELOG.md
  docs/tables/azure_network_virtual_network_ip_allocations.md
  docs/tables/azure_network_virtual_network_peerings.md
  docs/tables/azure_network_virtual_network_subnets.md
  docs/tables/azure_network_virtual_networks.md
  resources/provider/migrations/1_v0.3.8.down.sql
  resources/provider/migrations/1_v0.3.8.up.sql
  resources/provider/migrations/3_v0.3.11.down.sql
  resources/provider/migrations/3_v0.3.11.up.sql
  resources/services/network/virtual_networks.go
  resources/services/network/virtual_networks_mock_test.go
Labels: fix

#90 fix: Table `azure_network_public_ip_address_ip_tags` is json column of `azure_network_public_ip_addresses` now, some structure fixes
  docs/tables/azure_network_public_ip_address_ip_tags.md
  docs/tables/azure_network_public_ip_addresses.md
  resources/provider/migrations/3_v0.3.11.down.sql
  resources/provider/migrations/3_v0.3.11.up.sql
  resources/services/network/public_ip_addresses.go
  resources/services/network/public_ip_addresses_mock_test.go
Labels: fix

#118 feat: Testable Migrations
  .github/workflows/test_migration.yml
  client/testing.go
  go.mod
  go.sum
  resources/provider/migrations/1_v0.3.8.down.sql
  resources/provider/migrations/1_v0.3.8.up.sql
  resources/provider/migrations/2_v0.3.9.down.sql
  resources/provider/migrations/2_v0.3.9.up.sql
  resources/provider/migrations/3_v0.3.11.down.sql
  resources/provider/migrations/3_v0.3.11.up.sql
  resources/provider/migrations/postgres/4_v0.4.0.down.sql
  resources/provider/migrations/postgres/4_v0.4.0.up.sql
  resources/provider/migrations/timescale/4_v0.4.0.down.sql
  resources/provider/migrations/timescale/4_v0.4.0.up.sql
  resources/provider/provider.go
  resources/provider/provider_test.go
  tools/migrations/main.go
Labels: feat

#119 feat: Upgrade SDK v0.7.0
  go.mod
  go.sum
Labels: feat

#120 chore: Synced file(s) with cloudquery/.github
  .github/workflows/test_migration.yml
Labels: ignore-for-release

#114 feat: Finalize migration to the new testing sdk
  client/testing.go
  docs/tables/azure_compute_virtual_machines.md
  docs/tables/azure_network_public_ip_addresses.md
  docs/tables/azure_network_virtual_network_subnets.md
  docs/tables/azure_web_app_host_name_ssl_states.md
  resources/services/compute/disks.go
  resources/services/compute/virtual_machines.go
  resources/services/container/managed_clusters.go
  resources/services/monitor/activity_logs.go
  resources/services/monitor/log_profiles.go
  resources/services/mysql/servers.go
  resources/services/network/public_ip_addresses.go
  resources/services/network/security_groups.go
  resources/services/network/virtual_networks.go
  resources/services/postgresql/servers.go
  resources/services/resources/policy_assignments.go
  resources/services/sql/databases.go
  resources/services/sql/encryption_protectors.go
  resources/services/sql/servers.go
  resources/services/storage/accounts.go
  resources/services/storage/blob_services.go
  resources/services/storage/containers.go
  resources/services/web/app_auth_settings.go
  resources/services/web/apps.go
  terraform/compute.tf
  terraform/container.tf
  terraform/keyvault.tf
  terraform/monitor.tf
  terraform/mysql.tf
  terraform/network.tf
  terraform/network_security_groups.tf
  terraform/postgresql.tf
  terraform/provider.tf
  terraform/resource_group.tf
  terraform/security.tf
  terraform/sql.tf
  terraform/storage.tf
  terraform/terraform.tf
  terraform/web.tf
Labels: feat

#121 feat: Add Error Classifier
  client/errors.go
  resources/provider/provider.go
Labels: feat
