Repository cloudquery/cq-provider-azure, pull requests merged in 2022-04, with the labels that each got.

#217 feat: Added Express Route components
  client/services/mocks/network.go
  client/services/networks.go
  client/services/services.go
  docs/tables/azure_network_express_route_circuit_authorizations.md
  docs/tables/azure_network_express_route_circuit_connections.md
  docs/tables/azure_network_express_route_circuit_peerings.md
  docs/tables/azure_network_express_route_circuits.md
  docs/tables/azure_network_express_route_connections.md
  docs/tables/azure_network_express_route_gateways.md
  docs/tables/azure_network_express_route_links.md
  docs/tables/azure_network_express_route_ports.md
  docs/tables/azure_network_peer_express_route_circuit_connections.md
  docs/tables/azure_network_route_filter_rules.md
  docs/tables/azure_network_route_filters.md
  resources/provider/migrations/postgres/9_v0.9.0.down.sql
  resources/provider/migrations/postgres/9_v0.9.0.up.sql
  resources/provider/migrations/timescale/9_v0.9.0.down.sql
  resources/provider/migrations/timescale/9_v0.9.0.up.sql
  resources/provider/provider.go
  resources/services/network/express_route_circuits.go
  resources/services/network/express_route_circuits_mock_test.go
  resources/services/network/express_route_gateways.go
  resources/services/network/express_route_gateways_mock_test.go
  resources/services/network/express_route_ports.go
  resources/services/network/express_route_ports_mock_test.go
  resources/services/network/route_filters.go
  resources/services/network/route_filters_mock_test.go
Labels: feat

#226 fix: Null panic in azure_web_apps (vnet_connections column)
  resources/services/web/apps.go
Labels: fix

#229 feat: Don't fetch from disabled and deleted subscriptions
  client/client.go
Labels: feat

#230 fix: Fetch from default subscriptions for integration tests
  resources/provider/integration_test.go
Labels: fix

#242 fix: Error classifier
  client/errors.go
Labels: fix

#241 docs: Update authentication section from 'Getting Started' guide
  docs/index.md
Labels: docs

#248 chore: Upgrade SDK to 0.9.1
  client/client.go
  client/errors.go
  client/testing.go
  go.mod
  go.sum
Labels: ignore-for-release

#239 chore: Remove stale issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ignore-for-release
