Repository cloudquery/cq-provider-azure, pull requests merged in 2022-05, with the labels that each got.

#246 chore: Ignore local terraform files
  .gitignore
Labels: ignore-for-release

#243 chore: Add local terraform variables
  terraform/batch/local/variables.tf
  terraform/compute/local/.terraform.lock.hcl
  terraform/container/local/variables.tf
  terraform/cosmosdb/local/variables.tf
  terraform/datalake/local/variables.tf
  terraform/iothub/local/variables.tf
  terraform/keyvault/local/variables.tf
  terraform/logic/local/variables.tf
  terraform/mariadb/local/variables.tf
  terraform/monitor/local/variables.tf
  terraform/mysql/local/variables.tf
  terraform/postgresql/local/variables.tf
  terraform/redis/local/variables.tf
  terraform/search/local/variables.tf
  terraform/security/local/variables.tf
  terraform/servicebus/local/variables.tf
  terraform/sql/local/variables.tf
  terraform/streamanalytics/local/variables.tf
Labels: ignore-for-release

#234 chore: Add some network TF files
  terraform/network/local/main.tf
  terraform/network/modules/test/network.tf
  terraform/network/modules/test/providers.tf
  terraform/network/modules/test/terraform.tf
  terraform/network/modules/test/variables.tf
  terraform/network/prod/.terraform.lock.hcl
  terraform/network/prod/main.tf
  terraform/network/prod/terraform.tf
Labels: ignore-for-release

#258 chore(deps): Delete `dependabot.yml`
  .github/dependabot.yml
Labels: ignore-for-release

#261 test: Add cq-config for policy tests
  test/policy_cq_config.hcl
Labels: test

#284 fix: Added IgnoreError filter for diagnostic setting resource
  client/errors.go
Labels: automerge

#305 fix: Clasify Subscription Not Registered
  client/errors.go
Labels: automerge
