Repository cloudquery/cq-provider-azure, pull requests merged in 2022-02, with the labels that each got.

#125 feat: Add virtual network rules for sql servers
  client/services/mocks/monitor.go
  client/services/mocks/sql.go
  client/services/mocks/web.go
  client/services/services.go
  client/services/sql.go
  client/services/web.go
  docs/tables/azure_network_public_ip_addresses.md
  docs/tables/azure_sql_server_virtual_network_rules.md
  resources/provider/migrations/postgres/unreleased.down.sql
  resources/provider/migrations/postgres/unreleased.up.sql
  resources/provider/migrations/timescale/unreleased.down.sql
  resources/provider/migrations/timescale/unreleased.up.sql
  resources/services/network/public_ip_addresses.go
  resources/services/sql/servers.go
  resources/services/sql/servers_mock_test.go
Labels: feat

#129 chore: Delete duplicate workflows
  .github/workflows/golang_lint.yml
Labels: ignore-for-release

#126 feat: Implement Redis cache resource
  client/services/mocks/redis.go
  client/services/redis.go
  client/services/services.go
  docs/tables/azure_network_public_ip_addresses.md
  docs/tables/azure_redis_services.md
  resources/provider/migrations/postgres/5_v0.5.0.down.sql
  resources/provider/migrations/postgres/5_v0.5.0.up.sql
  resources/provider/migrations/timescale/5_v0.5.0.down.sql
  resources/provider/migrations/timescale/5_v0.5.0.up.sql
  resources/provider/provider.go
  resources/services/network/public_ip_addresses.go
  resources/services/redis/redis.go
  resources/services/redis/redis_mock_test.go
  resources/services/redis/redis_test.go
  terraform/redis.tf
Labels: feat

#130 feat: Update SDK, redact errors
  client/errors.go
  client/testing.go
  go.mod
  go.sum
Labels: feat

#132 feat: Add SQL Server Security Alert Policies
  client/services/mocks/sql.go
  client/services/services.go
  client/services/sql.go
  docs/tables/azure_sql_server_security_alert_policy.md
  resources/provider/migrations/postgres/5_v0.5.0.down.sql
  resources/provider/migrations/postgres/5_v0.5.0.up.sql
  resources/provider/migrations/timescale/5_v0.5.0.down.sql
  resources/provider/migrations/timescale/5_v0.5.0.up.sql
  resources/services/sql/servers.go
  resources/services/sql/servers_mock_test.go
Labels: feat

#137 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
Labels: ignore-for-release

#127 feat: Added missing fields to `compute_virtual_machine` and `compute_virtual_machine_resources`
  client/services/compute.go
  client/services/services.go
  docs/tables/azure_compute_virtual_machine_network_interfaces.md
  docs/tables/azure_compute_virtual_machine_resources.md
  docs/tables/azure_compute_virtual_machine_secret_vault_certificates.md
  docs/tables/azure_compute_virtual_machine_secrets.md
  docs/tables/azure_compute_virtual_machine_win_config_rm_listeners.md
  docs/tables/azure_compute_virtual_machines.md
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
  resources/services/compute/virtual_machines.go
Labels: feat

#139 feat: Implement resource links resource
  client/services/mocks/resources.go
  client/services/resources.go
  client/services/services.go
  docs/tables/azure_resources_links.md
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
  resources/provider/provider.go
  resources/services/resources/links.go
  resources/services/resources/links_mock_test.go
Labels: feat

#124 feat: Added jit network access policies
  client/services/mocks/security.go
  client/services/security.go
  docs/tables/azure_security_jit_network_access_policies.md
  docs/tables/azure_security_jit_network_access_policy_requests.md
  docs/tables/azure_security_jit_network_access_policy_virtual_machines.md
  go.mod
  go.sum
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
  resources/provider/provider.go
  resources/services/security/jit_network_access_policies.go
  resources/services/security/jit_network_access_policies_mock_test.go
Labels: feat

#142 feat: Update SDK for diag handling
  client/errors.go
  go.mod
  go.sum
Labels: feat

#140 feat: Implement Managed HSM resource
  client/services/keyvault.go
  client/services/mocks/keyvault.go
  client/services/services.go
  docs/tables/azure_keyvault_managed_hsm.md
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
  resources/provider/provider.go
  resources/services/keyvault/keyvault_managed_hsm.go
  resources/services/keyvault/keyvault_managed_hsm_test.go
Labels: feat

#136 feat: Added IPConfigurations and PrivateEndpoints to virtual_network_subnet
  docs/docs.go
  docs/tables/azure_network_virtual_network_subnets.md
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
  resources/services/network/virtual_networks.go
  resources/services/network/virtual_networks_mock_test.go
Labels: feat

#146 feat: Added eventhub namespaces
  client/services/eventhub.go
  client/services/mocks/eventhub.go
  client/services/security.go
  client/services/services.go
  docs/tables/azure_eventhub_namespace_encryption_key_vault_properties.md
  docs/tables/azure_eventhub_namespaces.md
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/eventhub/namespaces.go
  resources/services/eventhub/namespaces_mock_test.go
Labels: feat

#135 feat: Add cosmosdb support
  client/services/cosmosdb.go
  client/services/mocks/cosmosdb.go
  client/services/services.go
  docs/tables/azure_cosmosdb_account_cors.md
  docs/tables/azure_cosmosdb_account_failover_policies.md
  docs/tables/azure_cosmosdb_account_locations.md
  docs/tables/azure_cosmosdb_account_private_endpoint_connections.md
  docs/tables/azure_cosmosdb_account_read_locations.md
  docs/tables/azure_cosmosdb_account_write_locations.md
  docs/tables/azure_cosmosdb_accounts.md
  docs/tables/azure_cosmosdb_mongodb_databases.md
  docs/tables/azure_cosmosdb_sql_databases.md
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/cosmosdb/accounts.go
  resources/services/cosmosdb/accounts_mock_test.go
  resources/services/cosmosdb/mongodb_databases.go
  resources/services/cosmosdb/mongodb_databases_mock_test.go
  resources/services/cosmosdb/sql_databases.go
  resources/services/cosmosdb/sql_databases_mock_test.go
Labels: feat

#131 feat: Added sql managed instances
  client/services/mocks/sql.go
  client/services/services.go
  client/services/sql.go
  docs/tables/azure_sql_managed_database_vulnerability_assessment_scans.md
  docs/tables/azure_sql_managed_database_vulnerability_assessments.md
  docs/tables/azure_sql_managed_databases.md
  docs/tables/azure_sql_managed_instance_encryption_protectors.md
  docs/tables/azure_sql_managed_instance_private_endpoint_connections.md
  docs/tables/azure_sql_managed_instance_vulnerability_assessments.md
  docs/tables/azure_sql_managed_instances.md
  resources/provider/migrations/postgres/5_v0.5.0.up.sql
  resources/provider/migrations/postgres/6_v0.6.0.up.sql
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/5_v0.5.0.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/sql/managed_databases.go
  resources/services/sql/managed_instances.go
  resources/services/sql/managed_instances_mock_test.go
  terraform/sql_managed_instance.tf
Labels: feat

#141 feat: Added azure_compute_virtual_machine_scale_sets
  client/services/compute.go
  client/services/mocks/compute.go
  docs/tables/azure_compute_virtual_machine_scale_set_extensions.md
  docs/tables/azure_compute_virtual_machine_scale_set_os_profile_secrets.md
  docs/tables/azure_compute_virtual_machine_scale_sets.md
  resources/provider/migrations/postgres/6_v0.6.0.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/compute/virtual_machine_scale_sets.go
  resources/services/compute/virtual_machine_scale_sets_mock_test.go
Labels: feat

#143 feat: Added datalake store accounts
  client/services/datalake.go
  client/services/mocks/datalake.go
  client/services/services.go
  docs/tables/azure_datalake_analytics_account_compute_policies.md
  docs/tables/azure_datalake_analytics_account_data_lake_store_accounts.md
  docs/tables/azure_datalake_analytics_account_firewall_rules.md
  docs/tables/azure_datalake_analytics_account_storage_accounts.md
  docs/tables/azure_datalake_analytics_accounts.md
  docs/tables/azure_datalake_storage_account_firewall_rules.md
  docs/tables/azure_datalake_storage_account_trusted_id_providers.md
  docs/tables/azure_datalake_storage_account_virtual_network_rules.md
  docs/tables/azure_datalake_storage_accounts.md
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/datalake/analytics_accounts.go
  resources/services/datalake/analytics_accounts_mock_test.go
  resources/services/datalake/storage_accounts.go
  resources/services/datalake/storage_accounts_mock_test.go
  terraform/datalake.tf
Labels: feat

#138 feat: Added sql database vulnerability scans
  client/services/mocks/sql.go
  client/services/mocks/sql_database.go
  client/services/mocks/sql_managed_database.go
  client/services/mocks/sql_managed_instance.go
  client/services/mocks/sql_server.go
  client/services/services.go
  client/services/sql.go
  docs/tables/azure_sql_database_db_blob_auditing_policies.md
  docs/tables/azure_sql_database_db_threat_detection_policies.md
  docs/tables/azure_sql_database_db_vulnerability_assessment_scans.md
  docs/tables/azure_sql_database_db_vulnerability_assessments.md
  docs/tables/azure_sql_databases.md
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/6_v0.6.0.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/services/sql/databases.go
  resources/services/sql/servers.go
  resources/services/sql/servers_mock_test.go
Labels: feat

#147 feat: Implement MariaDB resource
  client/services/mariadb.go
  client/services/mocks/mariadb.go
  client/services/services.go
  docs/tables/azure_mariadb_server_configurations.md
  docs/tables/azure_mariadb_server_private_endpoint_connections.md
  docs/tables/azure_mariadb_servers.md
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/mariadb/servers.go
  resources/services/mariadb/servers_test.go
Labels: feat

#144 feat: Added network_interface and network_interface_ipconfigurations
  client/services/mocks/network.go
  client/services/networks.go
  client/services/services.go
  docs/tables/azure_network_interface_ip_configurations.md
  docs/tables/azure_network_interfaces.md
  resources/provider/migrations/postgres/8_v0.8.0.down.sql
  resources/provider/migrations/postgres/8_v0.8.0.up.sql
  resources/provider/migrations/timescale/8_v0.8.0.down.sql
  resources/provider/migrations/timescale/8_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/network/interfaces.go
  resources/services/network/interfaces_mock_test.go
Labels: feat

#145 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
Labels: ignore-for-release

#154 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
Labels: ignore-for-release

#153 feat: Implement Servicebus Namespaces resource
  client/services/mocks/servicebus.go
  client/services/servicebus.go
  client/services/services.go
  docs/tables/azure_mariadb_server_configurations.md
  docs/tables/azure_mariadb_server_private_endpoint_connections.md
  docs/tables/azure_servicebus_namespace_private_endpoint_connections.md
  docs/tables/azure_servicebus_namespaces.md
  docs/tables/azure_web_apps.md
  resources/provider/migrations/postgres/8_v0.8.0.down.sql
  resources/provider/migrations/postgres/8_v0.8.0.up.sql
  resources/provider/migrations/timescale/8_v0.8.0.down.sql
  resources/provider/migrations/timescale/8_v0.8.0.up.sql
  resources/provider/provider.go
  resources/services/mariadb/servers.go
  resources/services/servicebus/namespaces.go
  resources/services/servicebus/namespaces_test.go
  resources/services/web/apps.go
Labels: feat

#148 feat: Added iothub hubs
  client/services/iothub.go
  client/services/mocks/iothub.go
  client/services/services.go
  docs/tables/azure_iothub_hub_authorization_policies.md
  docs/tables/azure_iothub_hub_ip_filter_rules.md
  docs/tables/azure_iothub_hub_network_rule_sets_ip_rules.md
  docs/tables/azure_iothub_hub_private_endpoint_connections.md
  docs/tables/azure_iothub_hub_routing_endpoints_event_hubs.md
  docs/tables/azure_iothub_hub_routing_endpoints_service_bus_queues.md
  docs/tables/azure_iothub_hub_routing_endpoints_service_bus_topics.md
  docs/tables/azure_iothub_hub_routing_endpoints_storage_containers.md
  docs/tables/azure_iothub_hub_routing_routes.md
  docs/tables/azure_iothub_hubs.md
  resources/provider/migrations/postgres/9_v0.8.1.down.sql
  resources/provider/migrations/postgres/9_v0.8.1.up.sql
  resources/provider/migrations/timescale/9_v0.8.1.down.sql
  resources/provider/migrations/timescale/9_v0.8.1.up.sql
  resources/provider/provider.go
  resources/services/iothub/hubs.go
  resources/services/iothub/hubs_mock_test.go
Labels: feat

#150 feat: Added container registries
  client/services/containerregistry.go
  client/services/mocks/containerregistry.go
  client/services/services.go
  docs/tables/azure_container_registries.md
  docs/tables/azure_container_registry_network_rule_set_ip_rules.md
  docs/tables/azure_container_registry_network_rule_set_virtual_network_rules.md
  docs/tables/azure_container_registry_replications.md
  resources/provider/migrations/postgres/7_v0.6.1.down.sql
  resources/provider/migrations/postgres/7_v0.6.1.up.sql
  resources/provider/migrations/timescale/7_v0.6.1.down.sql
  resources/provider/migrations/timescale/7_v0.6.1.up.sql
  resources/provider/provider.go
  resources/services/container/container_registries.go
  resources/services/container/container_registries_mock_test.go
  resources/services/container/managed_clusters.go
  resources/services/container/managed_clusters_mock_test.go
Labels: feat

#160 fix: Failing resources again
  client/services/containerregistry.go
Labels: fix

#162 fix: Error classifier, update Azure SDK
  client/errors.go
  go.mod
  go.sum
  resources/services/monitor/activity_logs.go
Labels: fix

#163 fix: Ignore ListKeys 403 error for storage.accounts resource
  client/helpers.go
  resources/services/storage/accounts.go
Labels: fix

#161 feat: Fix in sql managed instances integration tests
  resources/services/container/container_registries.go
  resources/services/sql/managed_instances.go
Labels: feat

#167 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release
